### PR TITLE
adding txn.upsert rough draft

### PR DESCRIPTION
**Pull request by Kingloko**
This is a rough draft, a place to start a conversation. 
Hopefully this can be useful in upstream

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/pydgraph/89)

### CODE REVIEW

**Comment by Kingloko** [comment]
I actually think the wrapper has three major advantages (on top of the normal ease of use) 
**a) its easier for new users to quickly find.**
Personally, I had to search through the unit tests to figure out how to use the new upsert stuff, and if I was newer to dgraph I am not sure if I would have been able to find the feature as quickly as I did.
**b) It fits within the existing design,** txn.mutate and txn.query have wrappers so logically a new type of interaction should have its own new wrapper. 
**c) [could be related to a] it makes the code more readable**, if I was a new contributor to a team that uses dgraph it would be immedietly clear what txn.upsert().

Ultimately, this is your guys' product so you get the final say, this is just my two cents. As always, I appreciate the continuous support and quick responses.

**Comment by martinmr** [comment]
query and mutate exist as wrappers for backwards-compatibility reasons. My main issue with this wrapper is that we try to get the different clients to be as close as possible. So if the wrapper is useful, we should decide whether to bring it on every client. I'll bring up this discussion with the rest of the team to see what they think.

If you have specific complains about the upsert documentation, could you open an issue in the dgraph repo?

**Comment by Kingloko** [comment]
> query and mutate exist as wrappers for backwards-compatibility reasons. My main issue with this wrapper is that we try to get the different clients to be as close as possible. So if the wrapper is useful, we should decide whether to bring it on every client. I'll bring up this discussion with the rest of the team to see what they think.

That's a great point, keeping the APIs equivalent is something I hadn't considered. I'll update the PR with the information you all asked for later this week. 

Thanks for the quick review!

**Comment by mangalaman93** [comment]
@Kingloko We do not plan to add this in the library but we could add this as a test or an example. If you could raise a PR with that, would be happy to look at it.

**Pull request closed without merging**
