### PR TITLE
Initial draft of the python client.

### PR DESCRIPTION
**Pull request by mohitranka**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/pydgraph/1)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm_strong:  Clean and neat work. Thanks a lot @mohitranka. Go ahead and merge this.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pydgraph/client.py, line 39 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-KLv3viYoEH5vBxBc2HI:-KLv3viYoEH5vBxBc2HJ:1807873453) ([raw file](https://github.com/dgraph-io/pydgraph/blob/942bb4fec57c0934d9cc3ca072e75223c4e90f81/pydgraph/client.py#L39)):*
> ```Python
>         request = graphresponse_pb2.Request(query=q)
>         response = self.stub.Query(request, timeout)
>         return response
> ```

There is a line missing here probably.

---

*[pydgraph/test/test_queries.py, line 107 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-KLvC1_UtHi1Lcv8o1oO:-KLvC1_UtHi1Lcv8o1oP:-2105639210) ([raw file](https://github.com/dgraph-io/pydgraph/blob/942bb4fec57c0934d9cc3ca072e75223c4e90f81/pydgraph/test/test_queries.py#L107)):*
> ```Python
>         self.assertTrue(isinstance(response.l.parsing, basestring), 'Parsing latency is not available')
>         self.assertTrue(isinstance(response.l.pb, basestring), 'Protocol buffers latency is not available')
>         self.assertTrue(isinstance(response.l.processing, basestring), 'Processing latency is not available')
> ```

A line missing here too, shows this weird character.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-:-KLvBqzo20QOGd5_YOBd:1624545925)*

**Comment by mohitranka** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pydgraph/client.py, line 39 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-KLv3viYoEH5vBxBc2HI:-KLvDFSpGnOPLol3nNMn:1730422482) ([raw file](https://github.com/dgraph-io/pydgraph/blob/942bb4fec57c0934d9cc3ca072e75223c4e90f81/pydgraph/client.py#L39)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> There is a line missing here probably.
</details>
It just imply there is not a new line at the end of the file. Do you want me to change it and add a new line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pydgraph/client.py, line 39 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-KLv3viYoEH5vBxBc2HI:-KLvFyCIOHp8oUlyH0_t:-924142063) ([raw file](https://github.com/dgraph-io/pydgraph/blob/942bb4fec57c0934d9cc3ca072e75223c4e90f81/pydgraph/client.py#L39)):*
<details><summary><i>Previously, mohitranka (Mohit Ranka) wrote…</i></summary>
> It just imply there is not a new line at the end of the file. Do you want me to change it and add a new line?
</details>
It's probably a good convention for every line to end with a new line. That's why reviewable is showing this. 
Read this here http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1)*

**Comment by mohitranka** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pydgraph/client.py, line 39 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-KLv3viYoEH5vBxBc2HI:-KLvIezqtk29Q82BBTEX:-499146009) ([raw file](https://github.com/dgraph-io/pydgraph/blob/942bb4fec57c0934d9cc3ca072e75223c4e90f81/pydgraph/client.py#L39)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> It's probably a good convention for every line to end with a new line. That's why reviewable is showing this. 
> Read this here http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
</details>
Done.

---

*[pydgraph/test/test_queries.py, line 107 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-KLvC1_UtHi1Lcv8o1oO:-KLvIahh1STxEI97VoOY:-499146009) ([raw file](https://github.com/dgraph-io/pydgraph/blob/942bb4fec57c0934d9cc3ca072e75223c4e90f81/pydgraph/test/test_queries.py#L107)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> A line missing here too, shows this weird character.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/pydgraph/1#-:-KLvPkhuWNphqoBiME3m:1417088721)*

**Comment by mohitranka** [comment]
Merged to develop (via command line to be able to sign the commit.)

**Pull request closed without merging**
