### PR TITLE
add ai-classification notebook

### PR DESCRIPTION
**Pull request by rderbier**
Create contrib folder and add a first jupyter notebook

### CODE REVIEW

**Review by mangalaman93 — CHANGES_REQUESTED** [review]
Looks fine to me. Just one thing, that make sure it is rendered correctly on GitHub https://github.com/dgraph-io/pydgraph/blob/ba4dc585922ddf1c560ccb84e0c45f2400efb8eb/contrib/notebooks/dgraph-ai-classification.ipynb.

Also, maybe we want to add a list of these notebooks in the readme to explain what each notebook is for.

**Comment by rderbier** [comment]
added the list of ipynb files in readme.
The view in Github does not work well with the escape quotes used in the lambda string.
I'll try https://nbviewer.org/ but it does not work with branch. I'll check the nbviewer  after the merge.
The file must be used in VSCode, Colab or Jupyter notebook. It is not intend to be read in Github.

**Comment by mangalaman93** [comment]
No worries. At least one can read most of it, that's fine.

**Review by mangalaman93 — APPROVED** [review]

**Comment by joshua-goldstein** [comment]
I think the CI failure is related to this line 
```
discovered packages -- ['contrib', 'pydgraph', 'contrib.notebooks', 'pydgraph.proto']
```
i.e. the pip tooling thinks `contrib` is a python package and assumes it will find python modules there.  This might not be happening with `example` because example is an excluded name.  Is there a reason to use `contrib` over `example`?

**Comment by rderbier** [comment]
I moved to examples to follow the naming convention already started with the other notebook.

**Review by joshua-goldstein — APPROVED** [review]

**Pull request merged**
