### PR TITLE
Adding example for datetime parsing

### PR DESCRIPTION
**Pull request by mrwunderbar666**
@chewxy 
Pull request related to discussion: [Pydgraph (feature request): Automatically parse datetime strings](https://discuss.dgraph.io/t/pydgraph-feature-request-automatically-parse-datetime-strings/14074/5)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/pydgraph/170)

### CODE REVIEW

**Comment by chewxy** [comment]
reviewing now

**Review by chewxy — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/pydgraph/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrwunderbar666)

**Comment by chewxy** [comment]
p/s I have approved this PR. I'm making some fixes so TeamCity doesn't complain

**Review by tfalcao — APPROVED** [review]

**Comment by darkn3rd** [comment]
The current unit tests have problems, they should be fixed outside of this PR.   This is a solid example, I hope this is included.

**Comment by mrwunderbar666** [comment]
can we re-evaluate this pull request?

**Review by MichelDiz — APPROVED** [review]

**Comment by MichelDiz** [comment]
Thank you for your contribution @mrwunderbar666

**Pull request merged**
